### PR TITLE
replace String step from toInt() FragmentImpl method with a CharBuffer.

### PR DESCRIPTION
**Pull request by eemhu**
Previously, toString() was used in toInt() to first convert the byte array to UTF-8 string and integer was parsed from that string.

With these changes, the byte array is decoded with UTF-8 decoder and then the resulting char array is converted to integer.

(#60 )

### CODE REVIEW

**Comment by kortemik** [comment]
@StrongestNumber9 please performance test these
@eemhu test case would be appropriate for the new method, especially for handling overflow case and for non numeric data in the array

**Comment by eemhu** [comment]
> @StrongestNumber9 please performance test these @eemhu test case would be appropriate for the new method, especially for handling overflow case and for non numeric data in the array

New commit adds
* tests for both fragment.toInt() and charArrayToInt() methods.
* check for overflow in charArrayToInt()
* allow negative integer char array
* check for non-numeric chars

**Comment by StrongestNumber9** [comment]
> @StrongestNumber9 please performance test these @eemhu test case would be appropriate for the new method, especially for handling overflow case and for non numeric data in the array

Opened PR for @eemhu at https://github.com/eemhu/rlp_03/pull/1

**Comment by kortemik** [comment]
@StrongestNumber9 what is the performance difference compared to previous implementation?

**Comment by StrongestNumber9** [comment]
> @StrongestNumber9 what is the performance difference compared to previous implementation?

Slapped the test on top of commit e66110237b826f71e5a885bf3da949b4d2b3a89d from rlp_03 main branch
```sh
[positiveToIntPerformanceTest] Executed 100,000,000 loops in 3.29 seconds (30,358,228 eps)
[toBytesPerformanceTest] Executed 100,000,000 loops in 1.77 seconds (56,529,112 eps)
[toStringPerformanceTest] Executed 100,000,000 loops in 2.47 seconds (40,453,076 eps)
[negativeToIntPerformanceTest] Executed 100,000,000 loops in 3.12 seconds (32,051,284 eps)
```

New implementation on commit a02373964f9c91e045f813460e09145408f220ce from eemhu rlp_03 issue60 branch
```sh
[positiveToIntPerformanceTest] Executed 100,000,000 loops in 3.18 seconds (31,416,902 eps)
[toBytesPerformanceTest] Executed 100,000,000 loops in 1.77 seconds (56,401,580 eps)
[toStringPerformanceTest] Executed 100,000,000 loops in 2.49 seconds (40,080,164 eps)
[negativeToIntPerformanceTest] Executed 100,000,000 loops in 3.20 seconds (31,230,482 eps)
```

There might have been more load on my computer last time I ran these but so similar numbers points to either bottleneck somewhere or java optimizing it to (nearly) identical routes

**Comment by eemhu** [comment]
based on bytecode it does seem to call toString and parse the string to integer anyway, perhaps previous implementation is good enough?

**Comment by StrongestNumber9** [comment]
The LinkedList operations seems to be relatively heavy here as even forEaching them is heavy

image

**Comment by kortemik** [comment]
> based on bytecode it does seem to call toString and parse the string to integer anyway, perhaps previous implementation is good enough?

i agree, closing pr as previous implementation is more simple.

**Pull request closed without merging**
